#apiVersion: v1
#kind: Pod
#metadata:
#  name: 01-pod
#spec:
#  containers:
#    - name: nginx
#      image: nginx


#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: 02-pod
#spec:
#  initContainers:
#    - name: nginx-image
#      image: pavanidevops78/kubernetes:v1
#  containers:
#    - name: nginx
#      image: nginx
#
#---
apiVersion: v1
kind: Pod
metadata:
  name: 03-pod
spec:
  volumes:
    - name: nginx-volume
      emptyDir:
  initContainers:
    - name: nginx-init
      image: pavanidevops78/kubernetes:v1
      volumeMounts:
        - name: nginx-volume
          mountPath: /data
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-volume
          mountPath: /data

